### ISSUE TITLE
[FEATURE] add --ignore-platform-reqs to composer task

### ISSUE THREAD

**Issue by ervaude** [lightwerk/SurfTasks#10]
See: https://github.com/composer/composer/issues/1426

Since it is possible that the composer install tasks fails because of the php version of the SurfCaptain HostServer we should ignore php requirements when preparing a project for rsync. This requirement is only vital on the target server and not on the SurfCaptain-Server.
The option

--ignore-platform-reqs

does exactly that.

**Comment by achimfritz** [comment]
you can do this already in your preset-configuration (and we do it already)

```
"taskOptions": {
                    "typo3.surf:composer:install": {
                        "options": {
                            "composerCommandPath": "\/usr\/bin\/composer --ignore-platform-reqs"
                        }
                    }
                },
```

should be enough?

**Comment by ervaude** [comment]
Shouldn't that be default?

**Comment by achimfritz** [comment]
IMHO: No

**Comment by ervaude** [comment]
What is the benefit of testing the platform requirements of any project against the server where surf runs?
It makes little to no sense.
Now we have to add json by hand to the preset.json for every project that does not match the php version of a kind of random server ... 
Which is .... suboptimal to say the least.
