### ISSUE TITLE
lightwerk/SurfRunner dependency reference missing

### ISSUE THREAD

**Issue by p4t5h3** [lightwerk/SurfTasks#11]
When installing `lightwerk/SurfTasks` as a composer dependency in a project, `\Lightwerk\SurfTasks\Task\Database\CleanupTask` references:
- [`\Lightwerk\SurfRunner\Factory\NodeFactory`](https://github.com/lightwerk/SurfTasks/blob/master/Classes/Lightwerk/SurfTasks/Task/Database/CleanupTask.php#L9)
- [`\Lightwerk\SurfRunner\Factory\Exception`](https://github.com/lightwerk/SurfTasks/blob/master/Classes/Lightwerk/SurfTasks/Task/Database/CleanupTask.php#L44)

Resulting in the following exception (stack trace cut off):

```
Uncaught Exception: TYPO3\Flow\Core\Booting\Exception\SubProcessException

Message

  Uncaught Exception: TYPO3\Flow\Object\Exception\UnknownObjectException

  Message
    The object "Lightwerk\SurfRunner\Factory\NodeFactory" which was
  specified
    as a property in the object configuration of object
    "Lightwerk\SurfTasks\Task\Database\CleanupTask" (automatically
  registered
    class) does not exist. Check for spelling mistakes and if that
  dependency
    is correctly configured.

  More Information
    Exception code 1265213849
    File          
  Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/ProxyClassBuilder.php
  line 538
    Reference code 20150716113356a7cdf3
```

**Comment by ervaude** [comment]
Yes, this is on our ToDo List already. Sorry for the inconvenience.
